comment_width = 120
imports_granularity = "Crate"
match_block_trailing_comma = false
max_width = 100
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
