language: rust
sudo: false
cache: cargo

env:
  global:
    # Used on the deployment script
    - PROJECT_NAME=bat

matrix:
  allow_failures:
  - rust: nightly
  - os: windows

  fast_finish: true
  
  include:
  - rust: stable
  - rust: nightly

  - name: Clippy
    rust: nightly
    before_script: rustup component add clippy-preview
    script: cargo clippy --all -- -D clippy

  - name: rustfmt
    rust: nightly
    before_script: rustup component add rustfmt-preview
    script: cargo fmt --all -- --check

  - name: warnings
    rust: stable
    script: cargo check --all

  - name: release
    rust: stable
    script:
    - cargo build --all --release
    - cargo test --all --release
    - cargo doc --all --release
    on:
      tags: true

  - os: osx
    osx_image: xcode10

  - os: windows

  - os: linux

before_deploy: ci/deploy.sh

deploy:
  provider: releases
  file_glob: true
  file: pfiles/*
  skip_cleanup: true
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    #branch: master
    tags: true
  api_key:
    secure: PCRC1AYGYksGfRqUpNglgaOh2t+Jnmv/hd+K4ClScx2OQpjvFZyj1XTJsBN/Ze6VzyQR6dJH5b1g6LRSdF8qB364IOS5L4M6xFov9e1im14TrVDfGf7Dc5Qp4YvqKj+p6FcXwaLbq+AaDJeBfHVmgrI6TyjuYDmOMcaURMlzVCCeNpwkJobKji/Kua8HupYW+Tv/nviZtwhQJZ6EbjWjr65l5BdIEHpRiutjWDR14waa+Mx97ffInzoxCBtJJnU8RRz7uinxwXNF24vcJHy1eocZGJ/jt423beOGUE5NU42aSmXz3HpPquUf/WPp2Pc2SJOa0gK0ZVlu1BBxgO97lruQlQn285wFUDCX4EcrADtPHaTCCDp6YCKajBymEW6M60bKFMG/4YL4S9smYkLroy+dLUlUkBLLM+FdLRi0peYpfaJLHkga2z2/eA6xzHzqj3lrDkEfRgVa2aiJq5p3ZsBqBqKRNSVshZZr95GRmiVah5tsc5REKgOumyvhG8Fqt+MmG+ql502kT5aGhBxk3YswvzQZeUSB/8ACD2Lxc55vUE8Y9wbP4AGo59jPd6h/tC+9LDZRmKF2+20qtV5qfB4vl0JUyFtP7FComvN+I8dQSviH+PWOIvnPz2MCJs9f6xoBr4FAqqODpsMjqUTHMZYZzRufdBGp+aIBMQL2Qz0=

script:
- cargo build --all
- cargo test --all
- cargo doc --all
